version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=${SONARQUBE_USERNAME}
      - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_PASSWORD}
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${SONARQUBE_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SONARQUBE_ROOT_PASSWORD}
      - MYSQL_USER=${SONARQUBE_USERNAME}
      - MYSQL_PASSWORD=${SONARQUBE_PASSWORD}
